In [4]:
import pandas as pd
data = pd.read_csv('Loan_Default.csv')
pd.set_option('display.max_columns', None)

In [5]:
pd.set_option('display.max_rows', 100)
data.loc[(data["Upfront_charges"].isnull()) & (data["Status"]== 1)]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,116500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,118000.0,sb,pr,home,1U,1740.0,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,4980.0,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
10,24900,2019,cf,Male,nopre,type2,p3,l2,nopc,b/c,136500,NaN,NaN,NaN,300.0,neg_amm,not_int,not_lpsm,168000.0,sb,pr,home,1U,4020.0,EXP,723,CIB,55-64,to_inst,81.250000,North,direct,1,44.0
12,24902,2019,cf,Joint,nopre,type2,p3,l1,nopc,b/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,sb,pr,home,1U,3780.0,CRIF,884,EXP,65-74,to_inst,80.038760,North,direct,1,51.0
15,24905,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,76500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,138000.0,sb,pr,home,1U,2220.0,EXP,685,CIB,45-54,not_inst,55.434783,North,direct,1,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148651,173541,2019,cf,Joint,nopre,type3,p3,l1,nopc,nob/c,446500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,508000.0,sb,pr,home,1U,12300.0,EXP,897,EXP,45-54,to_inst,87.893701,North,direct,1,37.0
148652,173542,2019,cf,Male,nopre,type1,p1,l1,nopc,nob/c,96500,NaN,NaN,NaN,180.0,not_neg,not_int,not_lpsm,NaN,sb,ir,home,1U,5460.0,EQUI,608,EXP,55-64,to_inst,NaN,North,direct,1,NaN
148658,173548,2019,cf,Sex Not Available,nopre,type1,p4,l1,nopc,nob/c,386500,NaN,NaN,NaN,360.0,not_neg,int_only,not_lpsm,NaN,sb,pr,home,1U,4680.0,EQUI,669,EXP,25-34,to_inst,NaN,south,direct,1,NaN
148661,173551,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,346500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,358000.0,sb,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,96.787710,south,direct,1,NaN
148663,173553,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,106500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,1860.0,EQUI,619,EXP,<25,to_inst,NaN,North,direct,1,NaN

In [6]:
pd.set_option('display.max_rows', 100)
data.loc[(data["Upfront_charges"].isnull()) & (data["Status"]== 1)&(data["rate_of_interest"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,116500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,118000.0,sb,pr,home,1U,1740.0,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,4980.0,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
10,24900,2019,cf,Male,nopre,type2,p3,l2,nopc,b/c,136500,NaN,NaN,NaN,300.0,neg_amm,not_int,not_lpsm,168000.0,sb,pr,home,1U,4020.0,EXP,723,CIB,55-64,to_inst,81.250000,North,direct,1,44.0
12,24902,2019,cf,Joint,nopre,type2,p3,l1,nopc,b/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,sb,pr,home,1U,3780.0,CRIF,884,EXP,65-74,to_inst,80.038760,North,direct,1,51.0
15,24905,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,76500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,138000.0,sb,pr,home,1U,2220.0,EXP,685,CIB,45-54,not_inst,55.434783,North,direct,1,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148651,173541,2019,cf,Joint,nopre,type3,p3,l1,nopc,nob/c,446500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,508000.0,sb,pr,home,1U,12300.0,EXP,897,EXP,45-54,to_inst,87.893701,North,direct,1,37.0
148652,173542,2019,cf,Male,nopre,type1,p1,l1,nopc,nob/c,96500,NaN,NaN,NaN,180.0,not_neg,not_int,not_lpsm,NaN,sb,ir,home,1U,5460.0,EQUI,608,EXP,55-64,to_inst,NaN,North,direct,1,NaN
148658,173548,2019,cf,Sex Not Available,nopre,type1,p4,l1,nopc,nob/c,386500,NaN,NaN,NaN,360.0,not_neg,int_only,not_lpsm,NaN,sb,pr,home,1U,4680.0,EQUI,669,EXP,25-34,to_inst,NaN,south,direct,1,NaN
148661,173551,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,346500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,358000.0,sb,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,96.787710,south,direct,1,NaN
148663,173553,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,106500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,1860.0,EQUI,619,EXP,<25,to_inst,NaN,North,direct,1,NaN

In [7]:
pd.set_option('display.max_rows', 20)
data.loc[(data["Upfront_charges"].isnull()) & (data["Status"]== 1) & (~data["rate_of_interest"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
7205,32095,2019,ncf,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,86500,4.375,NaN,NaN,360.0,not_neg,not_int,not_lpsm,98000.0,sb,pr,home,1U,NaN,EQUI,584,EXP,NaN,NaN,88.265306,south,direct,1,NaN
7216,32106,2019,ncf,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,86500,4.250,NaN,NaN,360.0,not_neg,not_int,not_lpsm,108000.0,sb,pr,home,1U,NaN,EQUI,694,EXP,NaN,NaN,80.092593,south,direct,1,NaN
7263,32153,2019,ncf,Sex Not Available,nopre,type2,p3,l1,nopc,b/c,176500,3.750,NaN,NaN,360.0,not_neg,not_int,not_lpsm,218000.0,sb,pr,home,1U,NaN,EQUI,582,EXP,NaN,NaN,80.963303,south,direct,1,NaN
8053,32943,2019,ncf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,386500,4.750,NaN,NaN,360.0,not_neg,not_int,not_lpsm,428000.0,sb,pr,home,1U,NaN,EQUI,722,EXP,NaN,NaN,90.303738,south,direct,1,NaN
8862,33752,2019,ncf,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,256500,4.250,NaN,NaN,360.0,not_neg,not_int,not_lpsm,288000.0,sb,pr,home,1U,NaN,EQUI,771,EXP,NaN,NaN,89.062500,south,direct,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115205,140095,2019,ncf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,156500,3.125,NaN,NaN,180.0,not_neg,not_int,not_lpsm,218000.0,sb,pr,home,1U,NaN,EQUI,779,EXP,NaN,NaN,71.788991,south,direct,1,NaN
115577,140467,2019,NaN,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,206500,3.875,NaN,NaN,360.0,not_neg,not_int,not_lpsm,228000.0,sb,pr,home,1U,NaN,EQUI,695,EXP,NaN,NaN,90.570175,south,direct,1,NaN
118230,143120,2019,NaN,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,56500,4.375,NaN,NaN,360.0,not_neg,not_int,not_lpsm,78000.0,sb,pr,home,1U,NaN,EQUI,832,EXP,NaN,NaN,72.435897,south,direct,1,NaN
119922,144812,2019,ncf,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,96500,3.750,NaN,NaN,360.0,not_neg,not_int,not_lpsm,138000.0,sb,pr,home,1U,NaN,EQUI,702,EXP,NaN,NaN,69.927536,south,direct,1,NaN
132976,157866,2019,ncf,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,126500,4.250,NaN,NaN,360.0,not_neg,not_int,not_lpsm,148000.0,sb,pr,home,1U,NaN,EQUI,603,EXP,NaN,NaN,85.472973,south,direct,1,NaN

In [8]:
#Def. błędnej danej w deafaulcie(błedny default): Osoby nie mające null w rate_of_interest i mające status 1,
#mają null w age i w submission_of_application
#Mamy 36639 deafaultow zakładając, że 200 z nich to "blędy w danych", czyli 36439 to "prawdziwe defaulty", oczywiście w teorii
#Widzimy, że default charakteryzuje null w rate_of_interest i Interest_rate_spread
#Zauważamy, że każdy prawdziwy default ma null w upfront_charges, ale niektóre błędne defaulty mają wartość w upfront_charges,
#a niektóre nie mają (153:47)
#Wiec nowy def. prawdziwego defaultu: Osoby mające null w rate_of_interest, Interest_rate_spread, upfront_charges

In [9]:
#Badamy pozostałe 3156 nulle w braku defaultu (status 0), nie oznacza to 0 wkładu własnego (upfront_charges), bo istnieją wartości 0
pd.set_option('display.max_rows', 40)
data.loc[(data["Upfront_charges"].isnull()) & (data["Status"]== 0)]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,456500,4.250,0.6810,NaN,360.0,not_neg,not_int,not_lpsm,658000.0,sb,pr,home,1U,11880.0,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
59,24949,2019,cf,Sex Not Available,pre,type1,p3,l1,nopc,nob/c,426500,3.375,-0.0529,NaN,180.0,not_neg,not_int,not_lpsm,608000.0,sb,pr,home,1U,11340.0,CRIF,556,CIB,35-44,to_inst,70.148026,south,direct,0,27.0
68,24958,2019,NaN,Female,nopre,type2,p3,l1,nopc,b/c,226500,3.625,0.5626,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,sb,pr,home,1U,3720.0,CRIF,820,CIB,25-34,not_inst,87.790698,North,direct,0,40.0
82,24972,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,476500,3.990,0.2859,NaN,360.0,not_neg,int_only,not_lpsm,688000.0,sb,pr,home,1U,15180.0,CIB,634,EXP,45-54,to_inst,69.258721,south,direct,0,23.0
89,24979,2019,cf,Joint,nopre,type1,p3,l2,opc,nob/c,56500,4.500,0.2520,NaN,360.0,not_neg,int_only,not_lpsm,2008000.0,sb,pr,home,1U,7980.0,EXP,677,EXP,65-74,to_inst,2.813745,North,direct,0,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148380,173270,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,296500,3.750,0.9629,NaN,360.0,not_neg,not_int,not_lpsm,308000.0,sb,pr,home,1U,NaN,EXP,625,CIB,25-34,to_inst,96.266234,south,direct,0,NaN
148574,173464,2019,cf,Sex Not Available,pre,type1,p4,l1,nopc,nob/c,526500,3.990,0.3278,NaN,360.0,not_neg,not_int,not_lpsm,758000.0,sb,pr,home,1U,9480.0,CRIF,764,CIB,35-44,to_inst,69.459103,south,direct,0,36.0
148585,173475,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,436500,4.125,0.0377,NaN,360.0,not_neg,not_int,not_lpsm,488000.0,sb,pr,home,1U,4800.0,CRIF,696,CIB,35-44,not_inst,89.446721,south,direct,0,48.0
148598,173488,2019,cf,Joint,nopre,type3,p4,l2,nopc,nob/c,566500,3.990,-0.0337,NaN,360.0,not_neg,not_int,not_lpsm,628000.0,sb,pr,home,1U,NaN,EXP,666,EXP,25-34,not_inst,90.207006,North,direct,0,NaN
148628,173518,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,206500,3.750,0.1823,NaN,180.0,neg_amm,not_int,not_lpsm,308000.0,sb,pr,home,1U,6180.0,CRIF,809,EXP,35-44,to_inst,67.045455,North,direct,0,36.0

In [10]:
#Wniosek: Nie wiem, bo nic sie chyba nie wyroznia

In [11]:
#dtir,income,LTV,property_value - badanie nulli

In [12]:
data.loc[(data["income"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
13,24903,2019,cf,Joint,nopre,type2,p4,l1,nopc,b/c,436500,3.625,0.6146,0.00,360.0,not_neg,not_int,not_lpsm,508000.0,sb,pr,home,1U,NaN,CRIF,520,EXP,55-64,to_inst,85.925197,North,direct,0,NaN
31,24921,2019,cf,Male,nopre,type3,p4,l1,nopc,nob/c,216500,2.990,-0.6203,2101.63,360.0,not_neg,not_int,not_lpsm,228000.0,sb,pr,home,1U,NaN,CIB,705,CIB,55-64,to_inst,94.956140,North,direct,0,NaN
48,24938,2019,cf,Male,nopre,type3,p4,l1,nopc,nob/c,386500,2.750,-0.7794,3808.56,360.0,not_neg,not_int,not_lpsm,428000.0,sb,pr,home,1U,NaN,CIB,798,CIB,45-54,not_inst,90.303738,south,direct,0,NaN
87,24977,2019,cf,Sex Not Available,pre,type3,p4,l1,nopc,nob/c,246500,3.750,-0.1094,0.00,360.0,not_neg,not_int,not_lpsm,358000.0,sb,pr,home,1U,NaN,EXP,511,EXP,35-44,to_inst,68.854749,south,direct,0,NaN
96,24986,2019,ncf,Male,pre,type3,p4,l1,nopc,nob/c,286500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,sb,pr,home,1U,NaN,EXP,872,CIB,65-74,to_inst,111.046512,south,direct,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148594,173484,2019,ncf,Joint,nopre,type3,p4,l1,nopc,nob/c,516500,3.375,-0.3452,0.00,360.0,not_neg,not_int,not_lpsm,518000.0,sb,pr,home,1U,NaN,EXP,894,EXP,45-54,not_inst,99.710425,south,direct,0,NaN
148598,173488,2019,cf,Joint,nopre,type3,p4,l2,nopc,nob/c,566500,3.990,-0.0337,NaN,360.0,not_neg,not_int,not_lpsm,628000.0,sb,pr,home,1U,NaN,EXP,666,EXP,25-34,not_inst,90.207006,North,direct,0,NaN
148604,173494,2019,cf,Sex Not Available,nopre,type3,p4,l1,nopc,nob/c,216500,3.625,-0.0623,0.00,360.0,not_neg,not_int,not_lpsm,248000.0,sb,pr,home,1U,NaN,EXP,775,EXP,>74,to_inst,87.298387,south,direct,0,NaN
148646,173536,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,366500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,448000.0,sb,pr,home,1U,NaN,CIB,641,CIB,25-34,not_inst,81.808036,south,direct,1,NaN
148661,173551,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,346500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,358000.0,sb,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,96.787710,south,direct,1,NaN

In [13]:
data.loc[(data["income"].isnull()) & (~data["dtir1"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
855,25745,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,346500,3.250,-0.5052,0.0,276.0,not_neg,not_int,not_lpsm,1008000.0,sb,pr,home,1U,NaN,CRIF,632,CIB,55-64,to_inst,34.375000,North,direct,0,21.0
921,25811,2019,cf,Female,nopre,type1,p1,l1,nopc,nob/c,306500,NaN,NaN,NaN,360.0,neg_amm,not_int,not_lpsm,388000.0,sb,pr,home,1U,NaN,CIB,680,CIB,25-34,to_inst,78.994845,south,direct,1,44.0
6458,31348,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,486500,3.625,-0.1430,0.0,360.0,not_neg,not_int,not_lpsm,668000.0,sb,pr,home,1U,NaN,CRIF,514,CIB,35-44,to_inst,72.829341,North,direct,0,39.0
6785,31675,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,206500,4.125,0.0172,0.0,360.0,not_neg,not_int,not_lpsm,308000.0,sb,pr,home,1U,NaN,CRIF,531,CIB,45-54,to_inst,67.045455,south,direct,0,36.0
7825,32715,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,636500,3.750,0.1862,0.0,360.0,not_neg,not_int,not_lpsm,708000.0,sb,sr,home,1U,NaN,EXP,635,CIB,25-34,to_inst,89.901130,North,direct,0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141164,166054,2019,cf,Male,nopre,type1,p1,l1,nopc,nob/c,316500,3.500,-0.0878,0.0,360.0,not_neg,not_int,not_lpsm,518000.0,sb,sr,home,1U,NaN,EXP,755,CIB,55-64,to_inst,61.100386,North,direct,0,31.0
141844,166734,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,266500,3.625,-0.3971,0.0,360.0,not_neg,not_int,not_lpsm,758000.0,sb,pr,home,1U,NaN,CIB,504,CIB,55-64,to_inst,35.158311,North,direct,0,19.0
143595,168485,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,226500,3.990,0.5467,0.0,360.0,not_neg,not_int,not_lpsm,248000.0,sb,pr,home,1U,NaN,CRIF,877,CIB,25-34,to_inst,91.330645,North,direct,0,20.0
144128,169018,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,486500,3.375,-0.4318,0.0,360.0,not_neg,not_int,not_lpsm,928000.0,sb,pr,home,1U,NaN,CRIF,519,EXP,45-54,to_inst,52.424569,North,direct,0,12.0
147002,171892,2019,cf,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,86500,4.750,1.1695,2062.5,360.0,not_neg,not_int,not_lpsm,118000.0,sb,ir,home,1U,NaN,CIB,710,EXP,25-34,to_inst,73.305085,south,direct,0,25.0

In [14]:
data.loc[(data["Status"]==1) & (data["income"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
96,24986,2019,ncf,Male,pre,type3,p4,l1,nopc,nob/c,286500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,sb,pr,home,1U,NaN,EXP,872,CIB,65-74,to_inst,111.046512,south,direct,1,NaN
103,24993,2019,cf,Male,nopre,type2,p4,l1,nopc,b/c,346500,NaN,NaN,NaN,360.0,not_neg,int_only,not_lpsm,478000.0,sb,pr,home,1U,NaN,EXP,577,CIB,35-44,to_inst,72.489540,North,direct,1,NaN
175,25065,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,376500,NaN,NaN,NaN,360.0,neg_amm,not_int,not_lpsm,378000.0,sb,pr,home,1U,NaN,EXP,866,EXP,35-44,to_inst,99.603175,south,direct,1,NaN
266,25156,2019,ncf,Sex Not Available,nopre,type2,p1,l1,nopc,b/c,196500,3.75,NaN,0.0,324.0,neg_amm,not_int,not_lpsm,198000.0,sb,pr,home,1U,NaN,EQUI,768,EXP,NaN,NaN,99.242424,south,direct,1,NaN
428,25318,2019,ncf,Joint,nopre,type3,p4,l1,nopc,nob/c,516500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,498000.0,sb,pr,home,1U,NaN,CIB,759,EXP,55-64,not_inst,103.714859,North,direct,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148239,173129,2019,ncf,Sex Not Available,nopre,type2,p3,l1,nopc,b/c,356500,3.75,NaN,0.0,360.0,neg_amm,not_int,not_lpsm,488000.0,sb,pr,home,1U,NaN,EQUI,834,EXP,NaN,NaN,73.053279,south,direct,1,NaN
148373,173263,2019,ncf,Joint,nopre,type3,p4,l1,nopc,nob/c,626500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,808000.0,sb,pr,home,1U,NaN,CRIF,850,EXP,45-54,to_inst,77.537129,south,direct,1,NaN
148430,173320,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,236500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,278000.0,sb,pr,home,1U,NaN,EXP,732,CIB,35-44,to_inst,85.071942,south,direct,1,NaN
148646,173536,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,366500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,448000.0,sb,pr,home,1U,NaN,CIB,641,CIB,25-34,not_inst,81.808036,south,direct,1,NaN
148661,173551,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,346500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,358000.0,sb,pr,home,1U,NaN,EXP,585,CIB,25-34,to_inst,96.787710,south,direct,1,NaN

In [15]:
#Można to uznać za błąd(te 110 wierszy), bo osoby mające null w income mają wartość w dtir1(debt to income ratio)

In [16]:
data.loc[(data["LTV"].isnull()) & (~data["property_value"].isnull())]

Empty DataFrame
Columns: [ID, year, loan_limit, Gender, approv_in_adv, loan_type, loan_purpose, Credit_Worthiness, open_credit, business_or_commercial, loan_amount, rate_of_interest, Interest_rate_spread, Upfront_charges, term, Neg_ammortization, interest_only, lump_sum_payment, property_value, construction_type, occupancy_type, Secured_by, total_units, income, credit_type, Credit_Score, co-applicant_credit_type, age, submission_of_application, LTV, Region, Security_Type, Status, dtir1]
Index: []

In [17]:
#Tu poprawne dane, bo osoby mające null w LTV nie mają wartości w property_value

In [18]:
data.loc[(data["LTV"].isnull()) & (~data["dtir1"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
123808,148698,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,476500,4.500,0.1398,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,7020.0,CRIF,600,EXP,65-74,to_inst,NaN,south,direct,0,39.0
145931,170821,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,146500,4.125,0.4308,NaN,180.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,3960.0,CIB,793,CIB,55-64,to_inst,NaN,central,direct,0,24.0

In [19]:
data.loc[(data["Status"]==1) & (data["property_value"].isnull())& (~data["dtir1"].isnull())]

Empty DataFrame
Columns: [ID, year, loan_limit, Gender, approv_in_adv, loan_type, loan_purpose, Credit_Worthiness, open_credit, business_or_commercial, loan_amount, rate_of_interest, Interest_rate_spread, Upfront_charges, term, Neg_ammortization, interest_only, lump_sum_payment, property_value, construction_type, occupancy_type, Secured_by, total_units, income, credit_type, Credit_Score, co-applicant_credit_type, age, submission_of_application, LTV, Region, Security_Type, Status, dtir1]
Index: []

In [20]:
#Każdy null w LTV nie ma wartości w dtir1(oprócz 2, bo nie mają deafaultu),15098-15096=2

In [21]:
data.loc[(data["income"].isnull()) & (data["dtir1"].isnull())& (data["property_value"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
3636,28526,2019,cf,Joint,nopre,type1,p1,l1,nopc,nob/c,196500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,ir,home,1U,NaN,EQUI,816,EXP,25-34,to_inst,NaN,North,direct,1,NaN
7124,32014,2019,cf,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,216500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,644,EXP,45-54,to_inst,NaN,south,direct,1,NaN
31163,56053,2019,cf,Male,nopre,type3,p4,l1,nopc,nob/c,296500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,755,EXP,65-74,to_inst,NaN,central,direct,1,NaN
33043,57933,2019,cf,Sex Not Available,pre,type2,p4,l1,nopc,b/c,236500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,722,EXP,55-64,to_inst,NaN,south,direct,1,NaN
33950,58840,2019,cf,Joint,nopre,type1,p1,l2,nopc,nob/c,626500,NaN,NaN,NaN,300.0,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,823,EXP,25-34,to_inst,NaN,North,direct,1,NaN
53314,78204,2019,cf,Sex Not Available,nopre,type3,p4,l1,nopc,nob/c,256500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,679,EXP,65-74,to_inst,NaN,south,direct,1,NaN
54814,79704,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,366500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,NaN,EQUI,640,EXP,25-34,to_inst,NaN,south,direct,1,NaN
58448,83338,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,236500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,618,EXP,35-44,to_inst,NaN,south,direct,1,NaN
61719,86609,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,476500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,720,EXP,65-74,to_inst,NaN,central,direct,1,NaN
62350,87240,2019,cf,Sex Not Available,nopre,type3,p4,l1,nopc,nob/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,695,EXP,45-54,to_inst,NaN,south,direct,1,NaN
86935,111825,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,646500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,NaN,EQUI,567,EXP,>74,to_inst,NaN,south,direct,1,NaN
107911,132801,2019,ncf,Female,nopre,type1,p4,l1,nopc,nob/c,1166500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,880,EXP,35-44,to_inst,NaN,North,direct,1,NaN
113380,138270,2019,cf,Male,nopre,type3,p4,l1,nopc,nob/c,266500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,564,EXP,55-64,to_inst,NaN,North,direct,1,NaN
125324,150214,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,226500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,547,EXP,>74,to_inst,NaN,central,direct,1,NaN
130924,155814,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,166500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,677,EXP,55-64,to_inst,NaN,North,direct,1,NaN

In [22]:
data.loc[(data["income"].isnull()) & (data["dtir1"].isnull())& (data["property_value"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
3636,28526,2019,cf,Joint,nopre,type1,p1,l1,nopc,nob/c,196500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,ir,home,1U,NaN,EQUI,816,EXP,25-34,to_inst,NaN,North,direct,1,NaN
7124,32014,2019,cf,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,216500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,644,EXP,45-54,to_inst,NaN,south,direct,1,NaN
31163,56053,2019,cf,Male,nopre,type3,p4,l1,nopc,nob/c,296500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,755,EXP,65-74,to_inst,NaN,central,direct,1,NaN
33043,57933,2019,cf,Sex Not Available,pre,type2,p4,l1,nopc,b/c,236500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,722,EXP,55-64,to_inst,NaN,south,direct,1,NaN
33950,58840,2019,cf,Joint,nopre,type1,p1,l2,nopc,nob/c,626500,NaN,NaN,NaN,300.0,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,823,EXP,25-34,to_inst,NaN,North,direct,1,NaN
53314,78204,2019,cf,Sex Not Available,nopre,type3,p4,l1,nopc,nob/c,256500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,679,EXP,65-74,to_inst,NaN,south,direct,1,NaN
54814,79704,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,366500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,NaN,EQUI,640,EXP,25-34,to_inst,NaN,south,direct,1,NaN
58448,83338,2019,cf,Sex Not Available,nopre,type2,p4,l1,nopc,b/c,236500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,618,EXP,35-44,to_inst,NaN,south,direct,1,NaN
61719,86609,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,476500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,720,EXP,65-74,to_inst,NaN,central,direct,1,NaN
62350,87240,2019,cf,Sex Not Available,nopre,type3,p4,l1,nopc,nob/c,206500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,695,EXP,45-54,to_inst,NaN,south,direct,1,NaN
86935,111825,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,646500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,NaN,sb,pr,home,1U,NaN,EQUI,567,EXP,>74,to_inst,NaN,south,direct,1,NaN
107911,132801,2019,ncf,Female,nopre,type1,p4,l1,nopc,nob/c,1166500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,880,EXP,35-44,to_inst,NaN,North,direct,1,NaN
113380,138270,2019,cf,Male,nopre,type3,p4,l1,nopc,nob/c,266500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,564,EXP,55-64,to_inst,NaN,North,direct,1,NaN
125324,150214,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,226500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,547,EXP,>74,to_inst,NaN,central,direct,1,NaN
130924,155814,2019,cf,Female,nopre,type2,p4,l1,nopc,b/c,166500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,NaN,EQUI,677,EXP,55-64,to_inst,NaN,North,direct,1,NaN

In [23]:
#są nulle w income, dtir1, property_value i w LTV

In [24]:
data.loc[(data["income"].isnull()) & (~data["dtir1"].isnull())& (data["property_value"].isnull())]

Empty DataFrame
Columns: [ID, year, loan_limit, Gender, approv_in_adv, loan_type, loan_purpose, Credit_Worthiness, open_credit, business_or_commercial, loan_amount, rate_of_interest, Interest_rate_spread, Upfront_charges, term, Neg_ammortization, interest_only, lump_sum_payment, property_value, construction_type, occupancy_type, Secured_by, total_units, income, credit_type, Credit_Score, co-applicant_credit_type, age, submission_of_application, LTV, Region, Security_Type, Status, dtir1]
Index: []

In [25]:
#dtir1 jest nullem<=>income jest nullem i/lub property_value jest nullem(czyli LTV również nullem)

In [26]:

data.loc[(data["loan_limit"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
7,24897,2019,NaN,Female,nopre,type1,p4,l1,nopc,nob/c,266500,4.125,0.2975,5609.88,360.0,not_neg,not_int,not_lpsm,308000.0,sb,pr,home,1U,3780.0,CIB,863,CIB,55-64,to_inst,86.525974,North,direct,0,42.0
25,24915,2019,NaN,Joint,nopre,type1,p3,l1,nopc,nob/c,426500,4.990,1.2706,169.50,360.0,not_neg,not_int,not_lpsm,568000.0,sb,pr,home,1U,8940.0,EXP,533,EXP,45-54,not_inst,75.088028,North,direct,0,34.0
32,24922,2019,NaN,Male,nopre,type1,p1,l1,nopc,nob/c,306500,4.125,0.2848,3752.40,360.0,not_neg,not_int,not_lpsm,318000.0,sb,pr,home,1U,5580.0,EXP,701,CIB,35-44,not_inst,96.383648,North,direct,0,37.0
68,24958,2019,NaN,Female,nopre,type2,p3,l1,nopc,b/c,226500,3.625,0.5626,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,sb,pr,home,1U,3720.0,CRIF,820,CIB,25-34,not_inst,87.790698,North,direct,0,40.0
97,24987,2019,NaN,Sex Not Available,nopre,type1,p4,l1,nopc,nob/c,136500,3.625,0.5440,3817.34,180.0,not_neg,not_int,not_lpsm,208000.0,sb,pr,home,1U,3000.0,EXP,898,CIB,55-64,to_inst,65.625000,south,direct,0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148409,173299,2019,NaN,Male,nopre,type1,p3,l1,nopc,nob/c,196500,5.125,1.4162,765.58,360.0,not_neg,not_int,not_lpsm,288000.0,sb,ir,home,3U,16800.0,EXP,863,CIB,45-54,not_inst,68.229167,south,direct,0,31.0
148453,173343,2019,NaN,Male,nopre,type1,p2,l1,nopc,nob/c,256500,4.250,0.2190,1124.83,360.0,not_neg,not_int,not_lpsm,328000.0,sb,pr,home,1U,4020.0,CIB,750,CIB,25-34,not_inst,78.201220,North,direct,0,30.0
148458,173348,2019,NaN,Male,nopre,type3,p3,l1,nopc,nob/c,216500,NaN,NaN,NaN,360.0,neg_amm,not_int,not_lpsm,198000.0,sb,pr,home,1U,14640.0,CRIF,611,CIB,65-74,to_inst,109.343434,North,direct,1,15.0
148467,173357,2019,NaN,Joint,nopre,type1,p1,l1,nopc,nob/c,146500,4.250,0.1589,1055.96,360.0,not_neg,not_int,not_lpsm,198000.0,sb,pr,home,1U,2880.0,EXP,578,EXP,35-44,not_inst,73.989899,North,direct,0,31.0
148514,173404,2019,NaN,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,76500,3.750,1.3739,3050.00,180.0,not_neg,not_int,not_lpsm,138000.0,sb,pr,home,1U,3480.0,EXP,785,CIB,35-44,to_inst,55.434783,south,direct,0,9.0

In [27]:
#loan_limit_null==3334
data.loc[(data["loan_limit"].isnull()) & (data["approv_in_adv"]== "pre")]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
2535,27425,2019,NaN,Joint,pre,type2,p1,l1,nopc,b/c,226500,3.375,0.5498,6034.15,360.0,not_neg,not_int,not_lpsm,268000.0,sb,pr,home,1U,4560.0,EXP,663,EXP,55-64,to_inst,84.514925,North,direct,0,44.0
4113,29003,2019,NaN,Male,pre,type1,p1,l1,nopc,nob/c,226500,4.125,0.7775,6270.00,360.0,not_neg,not_int,not_lpsm,288000.0,sb,pr,home,1U,6300.0,CIB,625,CIB,55-64,to_inst,78.645833,North,direct,0,43.0
11798,36688,2019,NaN,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,116500,4.250,0.6753,3035.00,360.0,not_neg,not_int,not_lpsm,158000.0,sb,pr,home,1U,1620.0,CRIF,622,CIB,55-64,to_inst,73.734177,south,direct,0,49.0
11801,36691,2019,NaN,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,256500,3.500,0.5709,3437.50,180.0,not_neg,not_int,not_lpsm,868000.0,sb,pr,home,1U,7560.0,CIB,893,CIB,25-34,to_inst,29.550691,south,direct,0,43.0
12669,37559,2019,NaN,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,146500,4.875,1.1886,2137.66,360.0,not_neg,not_int,not_lpsm,148000.0,sb,pr,home,1U,3360.0,CRIF,526,CIB,25-34,to_inst,98.986486,south,direct,0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142934,167824,2019,NaN,Male,pre,type1,p1,l1,nopc,nob/c,276500,3.875,0.3255,0.00,360.0,not_neg,not_int,not_lpsm,288000.0,sb,pr,home,1U,4200.0,CRIF,829,CIB,45-54,to_inst,96.006944,North,direct,0,42.0
143877,168767,2019,NaN,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,406500,3.625,0.0891,3532.81,360.0,not_neg,not_int,not_lpsm,428000.0,sb,pr,home,1U,8880.0,CRIF,657,EXP,25-34,to_inst,94.976636,south,direct,0,41.0
144224,169114,2019,NaN,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,406500,2.990,0.2276,8355.00,180.0,not_neg,not_int,not_lpsm,588000.0,sb,pr,home,1U,10500.0,CRIF,880,CIB,55-64,to_inst,69.132653,south,direct,0,30.0
145186,170076,2019,NaN,Female,pre,type1,p1,l1,nopc,nob/c,406500,4.250,0.3581,1250.00,360.0,not_neg,not_int,not_lpsm,428000.0,sb,pr,home,1U,7740.0,CIB,802,CIB,35-44,to_inst,94.976636,North,direct,0,37.0
146045,170935,2019,NaN,Sex Not Available,pre,type1,p1,l1,nopc,nob/c,176500,4.375,0.6167,4620.00,360.0,not_neg,not_int,not_lpsm,228000.0,sb,pr,home,1U,5580.0,CIB,529,CIB,35-44,to_inst,77.412281,south,direct,0,46.0

In [28]:
data.value_counts("approv_in_adv")

approv_in_adv
nopre    124621
pre       23141
Name: count, dtype: int64

In [29]:
pd.set_option('display.max_rows', 15)
data.loc[(data["loan_purpose"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
3522,28412,2019,cf,Male,nopre,type1,NaN,l1,nopc,nob/c,406500,3.875,-0.4371,4780.00,360.0,not_neg,not_int,not_lpsm,628000.0,sb,pr,home,1U,8940.0,CIB,869,CIB,45-54,not_inst,64.729299,North,direct,0,44.0
3765,28655,2019,ncf,Male,pre,type1,NaN,l1,nopc,nob/c,1366500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,NaN,sb,pr,home,1U,18000.0,EQUI,643,EXP,45-54,to_inst,NaN,North,direct,1,NaN
6292,31182,2019,ncf,Joint,nopre,type3,NaN,l1,nopc,nob/c,496500,4.500,0.2344,0.00,360.0,not_neg,not_int,not_lpsm,488000.0,sb,pr,home,1U,8580.0,CIB,815,EXP,35-44,not_inst,101.741803,North,direct,0,34.0
7127,32017,2019,cf,Male,nopre,type1,NaN,l1,nopc,nob/c,496500,4.180,0.3087,5000.00,360.0,not_neg,not_int,not_lpsm,528000.0,sb,pr,home,1U,7620.0,CRIF,710,CIB,25-34,not_inst,94.034091,North,direct,0,39.0
9620,34510,2019,cf,Sex Not Available,pre,type1,NaN,l1,nopc,nob/c,176500,3.990,0.5039,1250.00,360.0,not_neg,not_int,not_lpsm,208000.0,sb,pr,home,1U,2340.0,CRIF,674,CIB,25-34,to_inst,84.855769,south,direct,0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147157,172047,2019,ncf,Joint,nopre,type1,NaN,l1,nopc,nob/c,226500,4.750,0.7476,1260.00,324.0,neg_amm,not_int,not_lpsm,318000.0,sb,pr,home,1U,7800.0,CIB,583,EXP,35-44,to_inst,71.226415,North,direct,0,36.0
147799,172689,2019,ncf,Sex Not Available,nopre,type2,NaN,l1,nopc,b/c,206500,3.990,NaN,0.00,360.0,neg_amm,not_int,not_lpsm,228000.0,sb,pr,home,1U,NaN,EQUI,527,EXP,NaN,NaN,90.570175,south,direct,1,NaN
147842,172732,2019,cf,Female,nopre,type2,NaN,l1,nopc,b/c,226500,4.125,0.8139,4051.52,360.0,not_neg,not_int,not_lpsm,238000.0,sb,pr,home,1U,3420.0,CRIF,824,CIB,45-54,to_inst,95.168067,central,direct,0,41.0
148233,173123,2019,cf,Joint,pre,type1,NaN,l1,nopc,nob/c,136500,3.990,0.4547,5042.70,360.0,not_neg,not_int,not_lpsm,168000.0,sb,pr,home,1U,6240.0,EXP,866,EXP,55-64,to_inst,81.250000,North,direct,0,43.0
148407,173297,2019,cf,Joint,pre,type1,NaN,l1,nopc,nob/c,166500,3.875,0.5740,2479.48,360.0,not_neg,not_int,not_lpsm,168000.0,sb,pr,home,1U,2880.0,EXP,611,EXP,55-64,to_inst,99.107143,North,direct,0,47.0

In [30]:
data.value_counts("Credit_Worthiness")

Credit_Worthiness
l1    142344
l2      6326
Name: count, dtype: int64

In [31]:
data.value_counts("open_credit")

open_credit
nopc    148114
opc        556
Name: count, dtype: int64

In [32]:
data.value_counts("interest_only")

interest_only
not_int     141560
int_only      7110
Name: count, dtype: int64

In [33]:
data.value_counts("construction_type")

construction_type
sb    148637
mh        33
Name: count, dtype: int64

In [34]:
data.value_counts("Secured_by")

Secured_by
home    148637
land        33
Name: count, dtype: int64

In [35]:
data.value_counts("lump_sum_payment")

lump_sum_payment
not_lpsm    145286
lpsm          3384
Name: count, dtype: int64

In [36]:
pd.set_option('display.max_rows', 15)
data.loc[(data["construction_type"]=="mh") & (data["Secured_by"]=="land")]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
7973,32863,2019,cf,Joint,nopre,type1,p1,l1,nopc,nob/c,126500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,138000.0,mh,pr,land,1U,4860.0,CRIF,847,EXP,25-34,to_inst,91.666667,North,Indriect,1,20.0
32312,57202,2019,cf,Sex Not Available,nopre,type1,p2,l1,nopc,nob/c,76500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,178000.0,mh,pr,land,1U,3660.0,CRIF,538,EXP,65-74,to_inst,42.977528,south,Indriect,1,41.0
34412,59302,2019,cf,Female,nopre,type1,p1,l1,nopc,nob/c,56500,NaN,NaN,NaN,360.0,neg_amm,not_int,not_lpsm,58000.0,mh,pr,land,1U,2340.0,CRIF,530,CIB,35-44,to_inst,97.413793,south,Indriect,1,33.0
35368,60258,2019,cf,Sex Not Available,nopre,type3,p4,l1,nopc,nob/c,396500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,428000.0,mh,pr,land,1U,NaN,EXP,576,EXP,35-44,to_inst,92.640187,south,Indriect,1,NaN
36155,61045,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,106500,NaN,NaN,NaN,360.0,neg_amm,not_int,not_lpsm,108000.0,mh,pr,land,1U,5700.0,CIB,758,CIB,25-34,to_inst,98.611111,North,Indriect,1,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125783,150673,2019,cf,Sex Not Available,nopre,type2,p3,l1,nopc,b/c,126500,NaN,NaN,NaN,180.0,not_neg,not_int,lpsm,168000.0,mh,pr,land,1U,2160.0,EXP,850,EXP,35-44,to_inst,75.297619,south,Indriect,1,42.0
128515,153405,2019,cf,Male,nopre,type2,p4,l1,nopc,b/c,216500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,258000.0,mh,pr,land,1U,5160.0,EXP,537,CIB,55-64,not_inst,83.914729,North,Indriect,1,37.0
140486,165376,2019,cf,Female,nopre,type1,p1,l1,nopc,nob/c,456500,NaN,NaN,NaN,360.0,not_neg,not_int,not_lpsm,508000.0,mh,sr,land,1U,30720.0,CRIF,883,CIB,35-44,not_inst,89.862205,North,Indriect,1,41.0
146525,171415,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,316500,NaN,NaN,NaN,360.0,not_neg,not_int,lpsm,428000.0,mh,pr,land,1U,10140.0,EXP,732,CIB,55-64,not_inst,73.948598,North,Indriect,1,22.0
148023,172913,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,376500,NaN,NaN,NaN,240.0,not_neg,not_int,not_lpsm,448000.0,mh,pr,land,1U,9000.0,CRIF,773,CIB,55-64,to_inst,84.040179,North,Indriect,1,30.0

In [37]:
#Wniosek:
#jeśli construction_type=="mh"(manufactured home) to Secured_by=="land"
#jeśli construction_type=="sb"(site built) to Secured_by=="home"

In [38]:
pd.set_option('display.max_rows', 50)
data.loc[(data["term"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
1187,26077,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,106500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,3420.0,EQUI,824,EXP,65-74,to_inst,NaN,south,direct,1,NaN
2228,27118,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,206500,3.875,0.0315,795.00,NaN,neg_amm,not_int,not_lpsm,438000.0,sb,pr,home,1U,8400.0,CIB,838,CIB,45-54,to_inst,47.146119,south,direct,0,25.0
4373,29263,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,126500,4.875,1.1345,1938.42,NaN,neg_amm,not_int,not_lpsm,218000.0,sb,pr,home,1U,5280.0,CIB,775,EXP,45-54,to_inst,58.027523,south,direct,0,44.0
4630,29520,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,476500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,508000.0,sb,pr,home,1U,16260.0,CRIF,721,EXP,55-64,to_inst,93.799213,North,direct,1,55.0
6087,30977,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,206500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,33540.0,EQUI,889,EXP,55-64,to_inst,NaN,North,direct,1,NaN
15166,40056,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,446500,3.990,0.2536,5570.00,NaN,neg_amm,not_int,not_lpsm,1158000.0,sb,pr,home,1U,9000.0,CIB,825,EXP,65-74,to_inst,38.557858,south,direct,0,44.0
17247,42137,2019,cf,Joint,nopre,type1,p3,l1,nopc,nob/c,276500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,5820.0,EQUI,738,EXP,55-64,to_inst,NaN,North,direct,1,NaN
18443,43333,2019,cf,Sex Not Available,nopre,type1,p2,l2,nopc,nob/c,216500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,sr,home,1U,38100.0,EQUI,623,EXP,65-74,to_inst,NaN,south,direct,1,NaN
19104,43994,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,216500,3.750,0.1709,4730.00,NaN,neg_amm,not_int,not_lpsm,338000.0,sb,pr,home,1U,8760.0,CIB,521,CIB,45-54,to_inst,64.053254,south,direct,0,20.0
28177,53067,2019,cf,Joint,nopre,type1,p4,l1,nopc,nob/c,146500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,4260.0,EQUI,563,EXP,35-44,to_inst,NaN,North,direct,1,NaN
28250,53140,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,76500,4.500,1.3061,2692.63,NaN,neg_amm,not_int,not_lpsm,198000.0,sb,pr,home,1U,3540.0,CIB,719,CIB,55-64,to_inst,38.636364,North,direct,0,20.0
32434,57324,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,106500,3.990,0.6261,NaN,NaN,neg_amm,not_int,not_lpsm,168000.0,sb,pr,home,1U,8940.0,CIB,778,EXP,65-74,to_inst,63.392857,south,direct,0,32.0
38598,63488,2019,cf,Joint,nopre,type1,p2,l1,nopc,nob/c,86500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,3780.0,EQUI,571,EXP,45-54,to_inst,NaN,North,direct,1,NaN
41303,66193,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,166500,4.625,1.2133,4000.00,NaN,neg_amm,not_int,not_lpsm,208000.0,sb,pr,home,1U,7920.0,CRIF,516,EXP,35-44,to_inst,80.048077,North,direct,0,41.0
48175,73065,2019,cf,Sex Not Available,nopre,type1,p4,l1,nopc,nob/c,106500,4.250,0.9586,NaN,NaN,neg_amm,not_int,not_lpsm,158000.0,sb,pr,home,1U,7560.0,EXP,639,CIB,55-64,to_inst,67.405063,south,direct,0,6.0
49997,74887,2019,cf,Male,pre,type1,p2,l1,nopc,nob/c,116500,4.750,1.1858,2250.00,NaN,neg_amm,not_int,not_lpsm,348000.0,sb,pr,home,1U,8040.0,EXP,821,CIB,55-64,to_inst,33.477011,North,direct,0,30.0
50583,75473,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,266500,2.750,-0.1732,9340.13,NaN,neg_amm,not_int,not_lpsm,788000.0,sb,pr,home,1U,4980.0,EXP,565,CIB,55-64,to_inst,33.819797,North,direct,0,43.0
53196,78086,2019,cf,Joint,nopre,type1,p3,l1,nopc,nob/c,156500,4.250,0.7264,3112.50,NaN,neg_amm,not_int,not_lpsm,238000.0,sb,pr,home,1U,3540.0,CRIF,752,EXP,55-64,to_inst,65.756303,North,direct,0,47.0
57028,81918,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,126500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,3600.0,EQUI,828,EXP,55-64,to_inst,NaN,south,direct,1,NaN
62811,87701,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,116500,4.250,0.9174,3350.00,NaN,neg_amm,not_int,not_lpsm,708000.0,sb,pr,home,1U,3060.0,EXP,511,CIB,65-74,to_inst,16.454802,North,direct,0,40.0
62873,87763,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,96500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,3240.0,EQUI,689,EXP,65-74,to_inst,NaN,south,direct,1,NaN
65760,90650,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,106500,4.125,0.6169,2750.00,NaN,neg_amm,not_int,not_lpsm,168000.0,sb,pr,home,1U,5160.0,CIB,611,EXP,55-64,to_inst,63.392857,south,direct,0,36.0
66820,91710,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,76500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,1528000.0,sb,pr,home,1U,8460.0,EXP,557,CIB,65-74,to_inst,5.006545,south,direct,1,42.0
68465,93355,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,336500,3.990,0.4053,6754.98,NaN,neg_amm,not_int,not_lpsm,608000.0,sb,pr,home,1U,6780.0,CIB,590,CIB,45-54,to_inst,55.345395,North,direct,0,43.0
73069,97959,2019,cf,Sex Not Available,nopre,type1,p4,l1,nopc,nob/c,206500,4.375,0.6498,2806.38,NaN,neg_amm,not_int,not_lpsm,1418000.0,sb,pr,home,1U,30660.0,EXP,790,CIB,45-54,to_inst,14.562764,south,direct,0,20.0
81823,106713,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,206500,4.250,0.5506,3930.87,NaN,neg_amm,not_int,not_lpsm,268000.0,sb,pr,home,1U,6960.0,CRIF,566,CIB,55-64,to_inst,77.052239,North-East,direct,0,34.0
81898,106788,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,286500,3.750,0.0193,5368.68,NaN,neg_amm,not_int,not_lpsm,818000.0,sb,pr,home,1U,9600.0,CIB,630,EXP,55-64,to_inst,35.024450,south,direct,0,37.0
84652,109542,2019,cf,Joint,nopre,type1,p3,l1,nopc,nob/c,136500,4.375,1.0354,3625.97,NaN,neg_amm,not_int,not_lpsm,218000.0,sb,pr,home,1U,5160.0,CIB,623,EXP,55-64,to_inst,62.614679,North,direct,0,30.0
88389,113279,2019,cf,Sex Not Available,nopre,type1,p4,l1,nopc,nob/c,196500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,5520.0,EQUI,550,EXP,65-74,to_inst,NaN,south,direct,1,NaN
90203,115093,2019,cf,Male,pre,type1,p4,l1,nopc,nob/c,66500,4.375,1.4877,2373.42,NaN,neg_amm,not_int,not_lpsm,208000.0,sb,pr,home,1U,2880.0,CIB,598,CIB,55-64,to_inst,31.971154,North,direct,0,37.0
91739,116629,2019,cf,Joint,nopre,type1,p4,l1,nopc,nob/c,86500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,4620.0,EQUI,773,EXP,55-64,to_inst,NaN,central,direct,1,NaN
99268,124158,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,156500,3.750,0.5641,5258.13,NaN,neg_amm,not_int,not_lpsm,268000.0,sb,pr,home,1U,5400.0,EXP,616,CIB,45-54,to_inst,58.395522,south,direct,0,42.0
108638,133528,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,76500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,408000.0,sb,pr,home,1U,1140.0,EXP,840,CIB,55-64,to_inst,18.750000,North,direct,1,52.0
113908,138798,2019,cf,Sex Not Available,nopre,type1,p2,l1,nopc,nob/c,106500,4.375,1.0622,2900.00,NaN,neg_amm,not_int,not_lpsm,308000.0,sb,pr,home,1U,8520.0,EXP,702,EXP,55-64,to_inst,34.577922,south,direct,0,37.0
117525,142415,2019,cf,Female,pre,type1,p3,l1,nopc,nob/c,156500,3.990,0.6648,4535.13,NaN,neg_amm,not_int,not_lpsm,468000.0,sb,pr,home,1U,4380.0,CRIF,523,CIB,55-64,to_inst,33.440171,North,direct,0,40.0
117603,142493,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,226500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,pr,home,1U,4500.0,EQUI,690,EXP,55-64,to_inst,NaN,south,direct,1,NaN
123706,148596,2019,cf,Joint,nopre,type1,p2,l1,nopc,nob/c,106500,NaN,NaN,NaN,NaN,neg_amm,not_int,not_lpsm,NaN,sb,ir,home,1U,8760.0,EQUI,728,EXP,65-74,not_inst,NaN,central,direct,1,NaN
131007,155897,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,206500,3.750,0.1425,3919.59,NaN,neg_amm,not_int,not_lpsm,318000.0,sb,pr,home,1U,4860.0,CIB,815,CIB,45-54,to_inst,64.937107,North,direct,0,47.0
131164,156054,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,226500,3.990,0.3446,3607.50,NaN,neg_amm,not_int,not_lpsm,398000.0,sb,pr,home,1U,8040.0,CIB,562,EXP,45-54,to_inst,56.909548,south,direct,0,30.0
143316,168206,2019,cf,Joint,nopre,type1,p3,l1,nopc,nob/c,206500,3.990,0.6924,5900.00,NaN,neg_amm,not_int,not_lpsm,278000.0,sb,pr,home,1U,10080.0,CRIF,658,EXP,45-54,to_inst,74.280576,central,direct,0,37.0
146409,171299,2019,cf,Male,nopre,type1,p3,l1,nopc,nob/c,106500,4.125,0.7862,3150.00,NaN,neg_amm,not_int,not_lpsm,208000.0,sb,pr,home,1U,2100.0,EXP,843,CIB,>74,to_inst,51.201923,central,direct,0,42.0

In [39]:
data.value_counts("Neg_ammortization")
#Jeśli term="null" to Neg_ammortization jest negatywne co nie jest typowe

Neg_ammortization
not_neg    133420
neg_amm     15129
Name: count, dtype: int64

In [40]:
data.value_counts("Security_Type")

Security_Type
direct      148637
Indriect        33
Name: count, dtype: int64

In [41]:
pd.set_option('display.max_rows', 10)
data.loc[(data["Neg_ammortization"].isnull())]

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,occupancy_type,Secured_by,total_units,income,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
2458,27348,2019,cf,Male,nopre,type3,p3,l1,nopc,nob/c,246500,4.500,0.1416,3600.00,360.0,NaN,not_int,not_lpsm,248000.0,sb,pr,home,1U,3900.0,CRIF,790,CIB,55-64,to_inst,99.395161,central,direct,0,47.0
4691,29581,2019,cf,Female,nopre,type1,p1,l1,nopc,nob/c,96500,4.625,0.6663,1912.50,360.0,NaN,not_int,not_lpsm,118000.0,sb,pr,home,1U,1020.0,CRIF,826,CIB,25-34,to_inst,81.779661,south,direct,0,49.0
5845,30735,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,356500,4.750,0.4791,6507.50,360.0,NaN,not_int,not_lpsm,488000.0,sb,pr,home,1U,7320.0,CRIF,510,EXP,55-64,to_inst,73.053279,south,direct,0,41.0
7452,32342,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,456500,4.500,0.7024,3392.50,360.0,NaN,not_int,not_lpsm,768000.0,sb,pr,home,1U,4200.0,CIB,896,CIB,65-74,to_inst,59.440104,south,direct,0,49.0
8219,33109,2019,ncf,Joint,nopre,type1,p3,l1,nopc,nob/c,556500,3.750,-0.1558,459.87,360.0,NaN,not_int,not_lpsm,1208000.0,sb,pr,home,1U,9420.0,CIB,757,EXP,65-74,to_inst,46.067881,central,direct,0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143376,168266,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,186500,NaN,NaN,NaN,360.0,NaN,not_int,not_lpsm,288000.0,sb,ir,home,1U,9420.0,CIB,623,CIB,55-64,to_inst,64.756944,south,direct,1,40.0
143780,168670,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,416500,4.750,0.2913,NaN,360.0,NaN,not_int,not_lpsm,498000.0,sb,pr,home,1U,13620.0,CRIF,811,EXP,45-54,to_inst,83.634538,south,direct,0,36.0
145279,170169,2019,cf,Male,nopre,type3,p3,l1,nopc,nob/c,106500,NaN,NaN,NaN,180.0,NaN,not_int,not_lpsm,NaN,sb,pr,home,1U,4080.0,EQUI,781,EXP,65-74,to_inst,NaN,central,direct,1,NaN
146531,171421,2019,cf,Female,nopre,type2,p3,l1,nopc,b/c,226500,3.990,0.8449,0.00,360.0,NaN,not_int,not_lpsm,268000.0,sb,pr,home,1U,3540.0,CIB,651,CIB,35-44,to_inst,84.514925,south,direct,0,54.0
147010,171900,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,486500,4.500,0.6686,795.00,360.0,NaN,not_int,not_lpsm,898000.0,sb,pr,home,1U,11100.0,CIB,857,CIB,65-74,to_inst,54.175947,North,direct,0,37.0

In [42]:
#Wnioski:
#1.Osoby mające null w rate_of_interest, Interest_rate_spread, upfront_charges to prawdziwe defaulty
#2.Fałszywe defaulty to osoby mające null w age i submission_of_application,nie mające nullu w rate_of_interest tym 
#samym mające null w Interst_rate_spread i czasem w upfront_charges tak jak osoby ze statusem 0(tylko częściej),jest ich 200
#3.Null w LTV jest wtedy i tylko wtedy,gdy(<=>) kiedy występuje null w property_value, co  jest poprawne
#4.Null w property_value jest zawsze <=> kiedy występuje null w dtir1, gdy występuje default,
#5.2 osoby mają null w property_value, wartość w dtir1, one mają 0 w statusie, to jedyne osoby z 0 w statusie i nullem 
#w property_value, może błąd
#5.Osoby mające null w income mają BARDZO CZĘSTO null w dtir1 oprócz 110 przypadków co budzi wątpliwości,
#bo zawsze powinny być nulle, ale przy statusie 0, null w income<=> null w dtir1 
#6.Osoby mające null dtir1 zawsze mają null w property_value lub w income lub w obu
#7.Jeśli term="null" to Neg_ammortization jest negatywne co nie jest typowe

#Nienullowe:
#jeśli construction_type=="mh"(manufactured home) to Secured_by=="land"
#jeśli construction_type=="sb"(site built) to Secured_by=="home"

#Pytania:
#1.O czym świadczą nulle w "loan_limit", "loan_purpose", "term", "Neg_ammortization"?
#2.Czemu jest tak duży związek nulla w property_value z nullami w dtir1?\
#3.O czym świadczą nulle w "Upfront_charges" w statusie 0?